services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask1
      - flask2
    networks:
      - app_network

  flask1:
    build: .
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    networks:
      - app_network

  flask2:
    build: .
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    networks:
      - app_network

networks:
  app_network:
    driver: bridge 