services:
  vote:
    build: ./vote
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier

  result:
    build: ./result
    ports:
      - "5001:80"
    networks:
      - back-tier

  worker:
    build: ./worker
    networks:
      - front-tier
      - back-tier

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - front-tier

  db:
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier: 