services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - app_network

  celery:
    build: .
    command: celery -A app worker -l info
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - app_network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge 